version: '3.3'

services:
  appserver:
    build: .
    volumes:
      - .:/app
    ports:
      - 6969:6969
    environment:
      BACKEND_URL: 'http://google.com'
    command: bundle exec rackup --host 0.0.0.0 --port 6969
