version: '3.3'

services:
  appserver:
    build: .
    volumes:
      - .:/app
    ports:
      - 6969:6969
    environment:
      # BACKEND_URL: 'http://httpbin.org/post'
      # BACKEND_URL: 'http://10.254.254.254:7070'
      BACKEND_URL: 'http://www.redbubble.test'
    command: bundle exec rackup --host 0.0.0.0 --port 6969
